<a href="https://colab.research.google.com/github/likhith-kumarn/Machine_Learning/blob/main/pipeline_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_curve,roc_auc_score
import warnings
warnings.filterwarnings("ignore")

In [6]:
# creating dataset
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000, n_features=10,       # number of features
                                        n_informative=6,     # number of useful feature
                                        n_redundant=2,       random_state= 42
)

In [12]:
df=pd.DataFrame(x,columns=[f"feature_{i}" for i in range(10)])
df["target"]=y
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,target
0,-1.030931,1.391626,0.547274,0.928932,-1.738880,1.250002,1.332551,1.578256,2.124722,-0.318434,0
1,-2.766254,1.247870,-0.303691,1.083145,0.710836,1.968202,-1.794192,2.346422,1.700778,-0.001190,1
2,-0.558987,0.299849,1.527071,0.360442,-1.360209,1.100793,-0.755951,1.331933,2.041105,-0.824404,0
3,-1.350289,-2.046078,-0.614264,0.126459,-0.783923,5.895026,-0.915477,-3.184768,-0.399260,-3.920960,0
4,-0.275754,-0.728495,0.027727,-0.660834,-1.928161,3.544945,1.446944,-1.111662,0.313766,-2.376528,0

In [14]:
df.target.head()

0    0
1    1
2    0
3    0
4    0
Name: target, dtype: int64

In [16]:
x=df.drop("target",axis=1)
y=df["target"]

In [17]:
x.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,-1.030931,1.391626,0.547274,0.928932,-1.738880,1.250002,1.332551,1.578256,2.124722,-0.318434
1,-2.766254,1.247870,-0.303691,1.083145,0.710836,1.968202,-1.794192,2.346422,1.700778,-0.001190
2,-0.558987,0.299849,1.527071,0.360442,-1.360209,1.100793,-0.755951,1.331933,2.041105,-0.824404
3,-1.350289,-2.046078,-0.614264,0.126459,-0.783923,5.895026,-0.915477,-3.184768,-0.399260,-3.920960
4,-0.275754,-0.728495,0.027727,-0.660834,-1.928161,3.544945,1.446944,-1.111662,0.313766,-2.376528

In [18]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: target, dtype: int64

In [20]:
x.shape

(1000, 10)

In [21]:
y.shape

(1000,)

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [23]:
#create pipeline
pipeline=Pipeline([
    ("scaler",StandardScaler()),
    ("model",RandomForestClassifier(random_state=42))
])

In [24]:
#Hyperparameter Tuning
param_grid={
    "model__n_estimators":[100,200],
    "model__max_depth":[5,10,None],
}

In [25]:
#GridSearchCV
grid_search=GridSearchCV(pipeline,param_grid,cv=5,scoring="accuracy")

In [26]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model',
                                        RandomForestClassifier(random_state=42))]),
             param_grid={'model__max_depth': [5, 10, None],
                         'model__n_estimators': [100, 200]},
             scoring='accuracy')

In [27]:
grid_search.best_params_

{'model__max_depth': None, 'model__n_estimators': 100}

In [28]:
y_pred=grid_search.predict(x_test)

In [29]:
accuracy_score(y_test,y_pred)

0.855